/**
 * Master Data Matrices for ITS Chía-Girardot
 * Following PMITS "Entregable # 1 V0" and Resolution 28675/2022
 */

const DOM = [
  {cod:'DOM-01',name:'Gestión de Tráfico',desc:'Planificación, control y optimización del flujo vehicular y la capacidad vial.'},
  {cod:'DOM-02',name:'Gestión de Emergencias',desc:'Coordinación de respuestas ante incidentes, siniestros y desastres en el corredor.'},
  {cod:'DOM-03',name:'Información al Viajero',desc:'Suministro de datos para la toma de decisiones antes y durante el viaje.'},
  {cod:'DOM-04',name:'Seguridad y Cumplimiento',desc:'Vigilancia normativa, control de infracciones y protección de la vida.'},
  {cod:'DOM-05',name:'Recaudo y Pagos',desc:'Gestión de transacciones financieras por el uso de la infraestructura.'},
  {cod:'DOM-06',name:'Gestión de Infraestructura',desc:'Monitoreo de la salud de activos físicos y condiciones ambientales.'},
];

const AS = [
  {cod:'AS-01',name:'Gestión de Incidentes y Eventos',desc:'Capacidades de detección automática, validación y respuesta coordinada ante anomalías en la vía (accidentes, vehículos detenidos, obstáculos). Objetivo: minimizar el tiempo de despeje y prevenir siniestros secundarios.'},
  {cod:'AS-02',name:'Información al Viajero',desc:'Difusión de datos dinámicos y alertas en tiempo real a través de canales directos (PMV) e indirectos (App, Web, APIs). Facilita la toma de decisiones informada del usuario durante su trayecto.'},
  {cod:'AS-03',name:'Operación de Tráfico y Movilidad',desc:'Monitoreo constante del flujo vehicular, conteo, clasificación y medición de velocidades. Optimiza la capacidad operativa de la infraestructura y gestiona los niveles de servicio del corredor.'},
  {cod:'AS-04',name:'Recaudo y Gestión de Peajes',desc:'Procesamiento de transacciones financieras manuales y electrónicas (Telepeaje). Gestiona la interoperabilidad, el paso por carriles y la auditoría de tráfico en estaciones de recaudo.'},
  {cod:'AS-05',name:'Seguridad Vial y Cumplimiento',desc:'Control normativo y sancionatorio. Incluye foto-detección de infracciones (velocidad, giros) y pesaje dinámico (WIM) para proteger la integridad del pavimento y la seguridad de los usuarios.'},
  {cod:'AS-06',name:'Mantenimiento y Clima',desc:'Monitoreo de variables meteorológicas adversas (niebla, lluvia, vientos) y salud de activos físicos. Permite gestión proactiva de la infraestructura basada en condiciones ambientales reales.'},
  {cod:'AS-07',name:'Transporte Público',desc:'Gestión de operaciones de transporte masivo, puntualidad y coordinación intermodal.'},
  {cod:'AS-08',name:'Carga y Logística',desc:'Administración de vehículos de carga, control de pesos y gestión de flotas comerciales.'},
  {cod:'AS-09',name:'Fiscalización Vial',desc:'Control de infracciones, verificación documental (SOAT, tecno-mecánica) y cumplimiento de restricciones vehiculares.'},
  {cod:'AS-10',name:'Gestión Multimodal',desc:'Integración de información de múltiples modos de transporte para planificación óptima de viaje.'},
  {cod:'AS-11',name:'Infraestructura y Activos',desc:'Monitoreo de la salud estructural de puentes, túneles, taludes y pavimentos. Soporte al mantenimiento predictivo con telemetría SHM.'},
  {cod:'AS-12',name:'Soberanía Digital y Continuidad',desc:'Gestión de ciberseguridad, continuidad operativa y gobernanza del dato como activo del Estado.'},
];

const SE = [
  {cod:'SE-ITS-1',name:'Servicio de suministro de información de tráfico',cat:'Servicio ITS Prioritario (PMITS)'},
  {cod:'SE-ITS-2',name:'Servicio de pago electrónico vehicular de la tasa de peajes',cat:'Servicio ITS Prioritario (PMITS)'},
  {cod:'SE-ITS-3',name:'Servicio de suministro de información de transporte público',cat:'Servicio ITS Prioritario (PMITS)'},
  {cod:'SE-ITS-4',name:'Servicio de gestión de siniestros viales inesperados',cat:'Servicio ITS Prioritario (PMITS)'},
  {cod:'SE-ITS-5',name:'Servicio de control de infracción de exceso de velocidad',cat:'Servicio ITS Prioritario (PMITS)'},
  {cod:'SE-ITS-6',name:'Servicio de apoyo a la administración de vehículos de carga',cat:'Servicio ITS Prioritario (PMITS)'},
  {cod:'SE-ITS-7',name:'Monitoreo ambiental y meteorológico',cat:'Complementario ISO 14813'},
  {cod:'SE-ITS-8',name:'Gestión de mantenimiento de la infraestructura',cat:'Complementario ISO 14813'},
  {cod:'SE-ITS-9',name:'Gestión de emergencias y desastres',cat:'Complementario ISO 14813'},
  {cod:'SE-ITS-10',name:'Gestión de la demanda de transporte',cat:'Complementario ISO 14813'},
  {cod:'SE-ITS-11',name:'Información de viaje multimodal',cat:'Complementario ISO 14813'},
];

const SUB = [
  {cod:'SUB-01',sigla:'TMS',name:'Traffic Management System',fn:'Gestión de Tráfico',desc:'Plataforma central para el monitoreo de flujos, niveles de servicio (LOS) y ejecución de planes de tráfico dinámicos.'},
  {cod:'SUB-02',sigla:'TIS',name:'Traveler Information System',fn:'Suministro de Información',desc:'Difusión de contenidos hacia PMV y canales digitales con soporte multimodal (Peatones/Ciclistas).'},
  {cod:'SUB-03',sigla:'EMS',name:'Emergency Management System',fn:'Gestión de Emergencias',desc:'Módulo de gestión de incidentes (IMS) que automatiza protocolos de respuesta y coordina el despacho de auxilio.'},
  {cod:'SUB-04',sigla:'VMS',name:'Video Management System',fn:'Gestión de Video',desc:'Administración de flujos de video, grabación, procesamiento de analítica DAI y visualización en Video Wall.'},
  {cod:'SUB-05',sigla:'EFC',name:'Electronic Fee Collection',fn:'Recaudo Electrónico',desc:'Back-office encargado del peaje interoperable (IPyG), validación de TAGs y gestión de transacciones.'},
  {cod:'SUB-06',sigla:'AMS',name:'Asset Management System',fn:'Gestión de Infraestructura',desc:'Control de actuadores y telemetría de salud de taludes, puentes y pavimentos. Soporte a mantenimiento predictivo.'},
  {cod:'SUB-07',sigla:'CVO',name:'Commercial Vehicle Operations',fn:'Gestión de Carga',desc:'Gestión de operaciones de vehículos comerciales, permisos de carga y control de flotas.'},
  {cod:'SUB-08',sigla:'TES',name:'Traffic Enforcement System',fn:'Cumplimiento y Seguridad',desc:'Sistema de foto-detección de infracciones, control de velocidad y gestión de comparendos electrónicos.'},
  {cod:'SUB-09',sigla:'ESS-M',name:'Environmental Sensor Management',fn:'Gestión Ambiental',desc:'Gestión de sensores de condiciones ambientales: temperatura, visibilidad, precipitación y vientos.'},
  {cod:'SUB-10',sigla:'ESB',name:'Enterprise Service Bus',fn:'Bus de Integración (SB)',desc:'Middleware de integración que orquesta el flujo de datos entre todos los subsistemas del CCO y plataformas externas.'},
  {cod:'SUB-11',sigla:'BIM-DT',name:'Digital Twin Framework',fn:'Gemelo Digital (DT)',desc:'Plataforma BIM/GIS para la creación y gestión del Gemelo Digital del corredor. Simulaciones predictivas.'},
  {cod:'SUB-12',sigla:'NMS',name:'Network Management System',fn:'Gestión de Red y Ciber',desc:'Monitoreo y gestión de la infraestructura de red, telecomunicaciones y ciberseguridad del ecosistema ITS.'},
];

const FN = [
  ['F-01','Gestión de datos adicionales','Recopila, actualiza y almacena información adicional, como información local, información relacionada con la vida, etc.'],
  ['F-02','Gestión de datos de tráfico integrado','La información del tráfico por carretera y la información del transporte público se gestionan de manera integrada.'],
  ['F-03','Gestión de datos de la red vial','El diseño geométrico de las carreteras y los datos de las instalaciones se actualizan y gestionan.'],
  ['F-04','Detección de vehículos','Se detecta el estado de los vehículos.'],
  ['F-05','Procesamiento de datos de detección de vehículos','Los datos recopilados de los detectores individuales se procesan, agregan y convierten a los datos de la sección de la carretera.'],
  ['F-06','Gestión de datos de identificación de vehículos','Se identifican los vehículos de la sonda y se gestiona la información.'],
  ['F-07','Reconocimiento de la ubicación de vehículos','Se recopilan datos para el reconocimiento de la ubicación del vehículo.'],
  ['F-08','Procesamiento de datos de ubicación de los vehículos','Los datos de ubicación del vehículo se procesan y agregan como datos de operación del vehículo.'],
  ['F-09','Recepción de informes de estado del tráfico','Los operadores de los centros de control ingresan información al recibir informes de estado del tráfico.'],
  ['F-10','Filmación de video','La situación de campo se filma utilizando CCTV.'],
  ['F-11','Recopilación y análisis de datos de tráfico','Los datos de varias fuentes se recopilan y analizan exhaustivamente.'],
  ['F-12','Producción de información de flujo de tráfico','La información de tráfico se produce de acuerdo con las estrategias de provisión de información.'],
  ['F-13','Monitoreo de las condiciones del tráfico','El operador monitorea las condiciones del flujo de tráfico utilizando videos e información de flujo de tráfico.'],
  ['F-14','Visualización de información de flujo de tráfico','La información del flujo de tráfico y los datos de video se muestran en los medios de suministro de información.'],
  ['F-15','Interfaz de viajero','Las consultas y preguntas son ingresadas por los viajeros y se muestra la información solicitada.'],
  ['F-16','Organización de planes de viaje','La información para decisiones relacionadas con la hora de salida, medios de transporte, viaje y rutas se produce.'],
  ['F-17','Cálculo de ruta óptima para viajeros','Se calcula la ruta óptima desde el punto de partida del viajero hasta el destino.'],
  ['F-18','Suministro de información para viajeros','Se integran datos adicionales y datos de tráfico para proporcionar la información solicitada por los viajeros.'],
  ['F-19','Suministro de información para conductores','Se integran datos adicionales y datos de tráfico para proporcionar la información a los conductores.'],
  ['F-20','Reconocimiento de dispositivo de control en el vehículo','Mediante este dispositivo, se reconoce la ubicación actual del vehículo.'],
  ['F-21','Interfaz de controlador','Herramienta para que los conductores realicen consultas y desplieguen información solicitada.'],
  ['F-22','Cálculo de ruta óptima para conductores','Ruta óptima desde la ubicación actual del conductor hasta el destino.'],
  ['F-23','Detección de vehículos que pasan (peaje)','El centro detecta los "siniestros" mediante CCTV.'],
  ['F-24','Reconocimiento de vehículos','Cualquier "siniestro" reportado o detectado por el centro es confirmado por el operador.'],
  ['F-25','Detección de identificación del dispositivo terminal','El centro genera información relacionada con "siniestros" confirmados.'],
  ['F-26','Clasificación del tipo de vehículo','El operador controla el progreso del "siniestro" mediante CCTV.'],
  ['F-27','Gestión de ingreso de información del vehículo','Las contramedidas o el nivel de respuesta se determinan.'],
  ['F-28','Filmación de vehículos que pasan (peaje)','El nivel de respuesta se determina en función de la contra estrategia establecida.'],
  ['F-29','Comunicación con la estación','Los datos procesados se almacenan, gestionan y utilizan.'],
  ['F-30','Peaje','Los datos recopilados se procesan y analizan para generar datos necesarios.'],
  ['F-31','Visualización del resultado del procesamiento','Los registros de operación de cada autobús se recopilan y procesan.'],
  ['F-32','Gestión de datos de peaje','La información de tráfico y los datos de ubicación de vehículos se recopilan y gestionan.'],
  ['F-33','Búsqueda de vehículos','Se monitorea la información de ubicación del vehículo.'],
  ['F-34','Notificación de peaje impago','Se detecta la violación de la operación del vehículo.'],
  ['F-35','Manejo de datos (peaje)','Los accidentes de tránsito se detectan.'],
  ['F-36','Gestión del sistema','Se despachan los vehículos.'],
  ['F-37','Recolección de información de operaciones del vehículo (TP)','Las rutas de autobuses se gestionan.'],
  ['F-38','Recolección de información del evento','Se suministra información del autobús.'],
  ['F-39','Recolección de información de ubicación del vehículo','Los datos se manejan.'],
  ['F-40','Transmisión de información','Los datos de apoyo administrativo se generan.'],
  ['F-41','Visualización de información de operación','Otras funciones gerenciales.'],
  ['F-42','Visualización de siniestros viales','Los datos de la colección de información se recopilan.'],
  ['F-43','Visualización de información de operación en violación de la ley','La información se visualiza.'],
  ['F-44','Recepción de información','La información se recibe.'],
  ['F-45','Recolección de información','La información se recopila.'],
  ['F-46','Monitoreo de la información de ubicación del vehículo','Se monitorea la ubicación del vehículo.'],
  ['F-47','Detección de operación de violación','Se detecta la operación de violación.'],
  ['F-48','Detección de accidentes de tránsito','Los accidentes de tránsito se detectan.'],
  ['F-49','Distribución de vehículos','Los vehículos se despachan.'],
  ['F-50','Gestión de rutas de autobuses','Las rutas de autobuses se gestionan.'],
  ['F-51','Suministro de información del autobús','Se suministra información del autobús.'],
  ['F-52','Manejo de datos (TP)','Los datos se manejan.'],
  ['F-53','Generación de datos para soporte administrativo','Los datos de apoyo administrativo se generan.'],
  ['F-54','Otras funciones gerenciales (TP)','Otras funciones gerenciales de transporte público.'],
  ['F-55','Recolección de información de operación del vehículo','La información de operación de los vehículos se recopila.'],
  ['F-56','Recolección de información del evento (TP-2)','Los eventos de transporte público se recopilan.'],
  ['F-57','Recolección de información de ubicación del vehículo (TP-2)','La ubicación de los vehículos de transporte público se recopila.'],
  ['F-58','Transmisión de información (TP-2)','La información se transmite al sistema central.'],
  ['F-59','Visualización de información de operación (TP-2)','La información de operación se visualiza.'],
  ['F-60','Visualización de accidentes de tránsito','Los accidentes de tránsito se visualizan.'],
  ['F-77','Entrada de fase de semáforo por plan','Los planes de semaforización se ingresan al sistema.'],
  ['F-78','Modificación del plan de semaforización','Los planes de semaforización se modifican dinámicamente.'],
  ['F-79','Configuración de grupos de intersección','Los grupos de intersección se configuran según la demanda.'],
  ['F-80','Gestión del estado operativo del semáforo','El estado operativo de los semáforos se gestiona.'],
  ['F-84','Filmación de vehículos que pasan','Los vehículos que pasan son filmados para análisis.'],
  ['F-85','Comunicación con la estación','Se mantiene comunicación entre el sistema de campo y la estación central.'],
  ['F-105','Recepción del informe del accidente de tránsito','Se reciben los informes de accidentes de tránsito.'],
  ['F-106','Detección de accidentes de tránsito','Los accidentes se detectan automáticamente (DAI).'],
  ['F-107','Confirmación de accidentes de tránsito','Los accidentes son confirmados por el operador o por el sistema.'],
  ['F-108','Generación de información sobre accidentes de tránsito','La información sobre los accidentes se genera.'],
  ['F-109','Monitoreo del progreso del accidente de tránsito','El progreso del accidente se monitorea.'],
  ['F-110','Determinación de contramedidas','Las contramedidas operativas se determinan.'],
  ['F-111','Gestión del flujo de tráfico','El flujo de tráfico se gestiona.'],
  ['F-112','Manejo de accidentes de tránsito','Los accidentes se manejan.'],
  ['F-113','Cooperación con agencia relacionada','Se coopera con las agencias de emergencia.'],
  ['F-114','Confirmación al cierre del caso accidente de tránsito','El caso del accidente se cierra formalmente.'],
  ['F-115','Producción de informes sobre accidentes de tránsito','Los informes de accidentes se producen.'],
  ['F-117','Retroalimentación Pedagógica de Velocidad','El radar pedagógico retroalimenta al conductor sobre su velocidad en tiempo real.'],
  ['F-118','Gestión de Velocidad Media por Tramo','La velocidad media por tramo se gestiona para garantizar la seguridad vial.'],
  ['F-119','Fiscalización Automática de Infracciones','Las infracciones de tránsito son detectadas y procesadas automáticamente.'],
  ['F-120','Monitoreo de Redes de Servicios e Interferencias','Las redes de servicios y las interferencias se monitoran continuamente.'],
  ['F-121','Orquestación de Integración de Datos (ESB)','El bus de integración orquesta el flujo de datos entre todos los subsistemas.'],
  ['F-122','Representación Visual en Gemelo Digital','Los datos del corredor se representan visualmente en el Gemelo Digital (BIM/DT).'],
];

const CC = [
  ['CC-01','CCTV','Vigilancia por Video','Supervisión Visual Continua: Capacidad de observar y verificar el estado real de la infraestructura en tiempo real.'],
  ['CC-02','AID','Detección de Incidentes','Identificación Proactiva de Peligros: Capacidad de alertar automáticamente sobre eventos disruptivos sin depender del ojo humano.'],
  ['CC-03','DMS / VMS','Mensajería Variable','Difusión Masiva de Información: Capacidad de comunicar mensajes estratégicos y alertas directamente al conductor en vía.'],
  ['CC-04','ECS / SOS','Llamada de Emergencia','Auxilio Inmediato al Usuario: Capacidad de establecer un canal de voz crítico para asistencia en situaciones de crisis.'],
  ['CC-05','VDS / TDS','Contadores de Tráfico','Caracterización Dinámica del Flujo: Capacidad de cuantificar y clasificar el volumen vehicular para decisiones operativas.'],
  ['CC-06','ESS / RWIS','Sensores Ambientales','Monitoreo de Condiciones Climáticas: Capacidad de medir variables del entorno que afectan la seguridad y la visibilidad.'],
  ['CC-07','WIM','Pesaje Dinámico','Control de Carga en Movimiento: Capacidad de monitorear pesos vehiculares por eje sin interrumpir la fluidez del tránsito.'],
  ['CC-08','GMS-I','Inclinometría Geotécnica','Vigilancia de Estabilidad de Suelos: Capacidad de detectar movimientos en taludes para prevenir obstrucciones por deslizamientos.'],
  ['CC-09','SMS / SBT','Monitoreo de Estructuras','Evaluación de Salud Estructural: Capacidad de monitorear tensiones en cables (Torones) y fatiga en puentes y obras de arte.'],
  ['CC-10','WLS','Monitoreo Hídrico','Detección de Riesgo Hidrológico: Capacidad de alertar sobre niveles críticos de agua en calzada y cauces de Ríos.'],
  ['CC-11','AVI / ETC','Peajes Electrónicos','Automatización de Transacciones: Capacidad de procesar cobros de tasa de uso sin detener el movimiento vehicular.'],
  ['CC-12','ALPR / LPR','Reconocimiento de Placas','Identificación Vehicular Automática: Capacidad de reconocer placas para gestión de seguridad, multas y trazabilidad.'],
  ['CC-13','SPD','Radar Pedagógico','Gestión del Comportamiento Vial: Capacidad de inducir hábitos de velocidad segura mediante interacción visual en tiempo real.'],
  ['CC-14','VSL','Velocidad Variable','Control Dinámico de Límites: Capacidad de ajustar la velocidad permitida según las condiciones de seguridad o congestión.'],
  ['CC-15','TCS','Control de Túneles','Gestión de Entornos Confinados: Capacidad de operar sistemas de Ventilación e iluminación en infraestructuras cerradas.'],
  ['CC-16','EVCS','Electrolineras','Soporte a la Movilidad Sostenible: Capacidad de proveer infraestructura de carga para la transición a vehículos eléctricos.'],
  ['CC-17','PAS','Megafonía Inteligente','Notificación Audible de Alcance: Capacidad de emitir instrucciones de voz masivas en puntos críticos o zonas de alta concentración.'],
  ['CC-18','BCS / VRU','Contador de Ciclistas','Cuantificación de Movilidad Alternativa: Capacidad de medir y proteger el flujo de usuarios no motorizados (ciclistas/peatones).'],
  ['CC-19','UAS / UAV','Drones de Inspección','Reconocimiento Aéreo Remoto: Capacidad de inspeccionar activos y eventos en puntos de difícil acceso o alta peligrosidad.'],
  ['CC-20','VIS / LGS','Gestión de Iluminación','Control Adaptativo de Visibilidad: Capacidad de ajustar la intensidad lumínica según la luz natural y la opacidad del aire.'],
  ['CC-21','CSG / IoT','Ciberseguridad e IoT','Protección de la Integridad Digital: Capacidad de blindar los datos y gestionar dispositivos inteligentes de forma segura.'],
  ['CC-22','PSV','Seguridad Ciudadana','Protección Civil Integrada: Capacidad de enlazar sistemas de video y pánico con entes de seguridad pública y policía.'],
  ['CC-23','FOC','Conectividad de Fibra','Transporte de Datos de Alta Fidelidad: Capacidad de garantizar la comunicación fluida y robusta (incluye fibra de emergencia).'],
  ['CC-24','RCS','Comunicación Radial','Respaldo de Enlace Operativo: Capacidad de mantener comunicación con equipos de campo ante fallas de la red digital.'],
  ['CC-25','SME','Gestión de Medios Sociales','Omnicanalidad Digital: Capacidad de integrar Redes Sociales y analítica web como sensores y canales de respuesta al usuario.'],
  ['CC-26','RSU','Comunicación V2X','Conectividad con Vehículos Inteligentes: Capacidad de intercambiar datos técnicos con la nueva generación de vehículos conectados.'],
  ['CC-27','AVL / OBU','Control de Flota','Gestión Logística de Auxilio: Capacidad de rastrear y despachar eficientemente recursos de Ambulancia y Grúa.'],
  ['CC-28','PGS','Gestión de Parqueaderos','Optimización de Zonas de Servicio: Capacidad de guiar al usuario hacia plazas disponibles en estacionamientos y áreas de descanso.'],
  ['CC-29','SLP','Iluminación Solar','Autonomía Energética Sostenible: Capacidad de proveer alumbrado en vía mediante Paneles Solares y fuentes renovables.'],
  ['CC-30','LHD','Detección de Incendio','Identificación Térmica Lineal: Capacidad de detectar fuego de forma inmediata a lo largo de infraestructuras críticas y túneles.'],
  ['CC-31','AQM','Calidad del Aire','Monitoreo Ambiental Estratégico: Capacidad de medir índices de contaminación para soporte a políticas de movilidad sostenible.'],
  ['CC-37','WDA','Detección de Fauna','Protección Ecológica y Seguridad: Capacidad de detectar animales en la calzada para evitar colisiones en zonas ecológicas.'],
  ['CC-39','MSG','Micro-Red Inteligente','Gestión Energética Distribuida: Capacidad de balancear la carga eléctrica y gestionar generación renovable in-situ.'],
  ['CC-40','D-TWN','Nodos de Gemelo Digital','Visualización Digital del Corredor: Capacidad de representar en tiempo real el estado integral de la infraestructura en 3D.'],
  ['CC-42','SAT-B','Respaldo Satelital','Continuidad de Misión Crítica: Capacidad de garantizar comunicaciones esenciales ante falla total de la red terrestre.'],
];
