/**
 * EOV (Escenarios Operativos Vigentes) Data
 * Following PMITS "Entregable # 1 V0"
 * Cleaned and Restructured for Fidelity
 */

const EOV = [
  {
    "id": "EOV-1",
    "ico": "🚨",
    "type": "p",
    "name": "GESTIÓN DE LA VIDA Y SEGURIDAD VIAL",
    "ctx": "Monitoreo preventivo de conductas de riesgo y detección de vulnerabilidades en el corredor.",
    "mot": "Reducción de la siniestralidad vial mediante tecnología de fiscalización y pedagogía.",
    "que": "Sistema de radares pedagógicos, cámaras ALPR y CCTV integrados.",
    "para": "Sirve para inducir la autorregulación voluntaria de la velocidad, detectar intrusiones de usuarios vulnerables y recolectar evidencia técnica de infracciones para el fortalecimiento de la disciplina de tráfico.",
    "donde": "Infraestructura de vía Arterial principal y ramales de vías Colectoras con alta interacción peatonal.",
    "cuando": "Operación permanente y dinámica (24/7/365), con escalamiento durante periodos de visibilidad reducida.",
    "just": "Maximizar la eficiencia de la vigilancia operativa, permitiendo una cobertura geográfica extensa y una reacción en milisegundos que supera la capacidad de la presencia física policial.",
    "desp": "Distribución táctica de estaciones de control compuestas por radares pedagógicos y cámaras ALPR, interconectadas por fibra óptica.",
    "beneficio": "Salvamento de vidas humanas, reducción de la discapacidad por accidentes y fomento de una cultura de respeto vial.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-02",
    "area": "AS-01",
    "sub": "SUB-03",
    "se": "SE-ITS-4",
    "fn": "F-117 / F-118 / F-119",
    "cc": "CC-13 / CC-12 / CC-01",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Protocolos de Encriptación de Datos de Tráfico",
    "e1": "Gobernanza y Estrategia de Seguridad Vial PMITS",
    "e2": "Validación operativa por CCO y actualización de canales informativos.",
    "e3": "Ejecución de lógica algorítmica de retroalimentación pedagógica.",
    "e4": "Orquestación sistémica en SUB-04 VMS para filtrado de datos.",
    "e5": "Captura de variables físicas mediante CC-13 y registro visual con CC-12.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "contingencia": ["Energía: UPS / Solar", "Fibra: Satelital", "Vandalismo: Drones", "Redundancia Lógica", "Protocolo Manual"],
    "criterios": ["Uptime >99.5%", "Precisión >95%", "Integración 100%", "Latencia <500ms", "QA Técnico 100%"],
    "evol": ["IA Predictiva", "Conectividad V2X", "Gemelo Digital 3D", "Autonomía Total", "Blockchain Transaccional"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-2",
    "ico": "🚦",
    "type": "p",
    "name": "GESTIÓN DE TRÁFICO Y MOVILIDAD",
    "para": "Sirve para monitorear los Niveles de Servicio (LOS) de manera continua, identificar cuellos de botella incipientes y desplegar estrategias de tráfico dinámicas antes de que se consolide la congestión.",
    "donde": "Calzada Arterial principal e intersecciones con vías Colectoras de distribución urbana y regional.",
    "cuando": "Vigilancia permanente con protocolos reforzados durante picos de demanda estacional (Planes Éxodo/Retorno).",
    "just": "Gestión científica del tráfico que reemplace la intuición operativa con datos precisos de volumen, velocidad y ocupación.",
    "desp": "Sensores de conteo y cámaras de video-analítica integrados al subsistema TMS.",
    "beneficio": "Mejora en la competitividad logística, ahorro de tiempo productivo y reducción del estrés de conducción.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-01",
    "area": "AS-03",
    "sub": "SUB-03",
    "se": "SE-ITS-1",
    "fn": "F-01 / F-02 / F-10",
    "cc": "CC-05 / CC-01 / CC-03",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Seguridad en Bus de Servicios (SB)",
    "e1": "Optimización de Niveles de Servicio (LOS) Corredor 5G",
    "e2": "Ejecución de planes de información al viajero mediante CC-03 DMS.",
    "e3": "Aplicación de lógica F-02 para integración de datos de tráfico.",
    "e4": "Procesamiento y agregación de variables macroscópicas en SUB-01 TMS.",
    "e5": "Captura masiva de flujos con CC-05 y monitoreo visual con CC-01.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "contingencia": ["Energía: UPS / Solar", "Fibra: Satelital", "Vandalismo: Drones", "Redundancia Lógica", "Protocolo Manual"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-3",
    "ico": "⚖️",
    "type": "p",
    "name": "GESTIÓN DE CARGA Y PESAJE (WIM)",
    "para": "Sirve para realizar un control de carga sin detener el flujo logístico, recolectar analítica de fatiga estructural y alertar sobre vehículos infractores.",
    "donde": "Accesos al corredor y puntos previos a estructuras críticas (puentes, túneles).",
    "cuando": "Vigilancia transaccional continua (24/7), procesando cada vehículo de carga pesada.",
    "just": "Prevención de fallas estructurales catastróficas y equidad en la operación logística nacional.",
    "desp": "Básculas dinámicas integradas en pavimento y cámaras ALPR de alta velocidad.",
    "beneficio": "Asegura la longevidad de la infraestructura vial y reduce riesgo de accidentes por volcamiento.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-01",
    "area": "AS-01",
    "sub": "SUB-03",
    "se": "SE-ITS-1",
    "fn": "F-47 / F-02 / F-121",
    "cc": "CC-07 / CC-12 / CC-03",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Validación de Integridad de Datos WIM",
    "e1": "Preservación de Activos de Infraestructura y Control de Carga",
    "e2": "Notificación en tiempo real al conductor a través de CC-03 DMS.",
    "e3": "Activación de lógica F-47 para monitoreo de sobrepesos.",
    "e4": "Validación de transacción en SUB-01 TMS contra base de datos.",
    "e5": "Detección de masa y pesos por eje mediante CC-07 WIM.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-4",
    "ico": "🌧️",
    "type": "p",
    "name": "GESTIÓN DE RESILIENCIA CLIMÁTICA",
    "para": "Sirve para detectar alertas tempranas de inundación, niebla densa o vientos fuertes, permitiendo cierres preventivos y ajustes de velocidad.",
    "donde": "Puntos geográficos vulnerables (puentes sobre ríos, zonas de microclima cerrado).",
    "cuando": "Vigilancia pasiva permanente con transición a crítica durante eventos meteorológicos.",
    "just": "Proveer una base de datos científicos que elimina la subjetividad en la toma de decisiones de restricción.",
    "desp": "Estaciones meteorológicas y sensores de nivel de río integrados al CCO.",
    "beneficio": "Garantiza conectividad segura bajo clima extremo, protegiendo vidas e integridad de mercancías.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-02",
    "area": "AS-01",
    "sub": "SUB-03",
    "se": "SE-ITS-4",
    "fn": "F-84 / F-85 / F-116",
    "cc": "CC-06 / CC-10 / CC-03",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Sistemas de Alerta Estándar DATEX II",
    "e1": "Resiliencia Operativa ante Eventos Hidrometeorológicos",
    "e2": "Publicación de alertas en CC-03 DMS y ajuste de límites de velocidad.",
    "e3": "Ejecución de función F-84 para monitoreo ambiental.",
    "e4": "Integración y análisis de criticidad en SUB-12 NMS.",
    "e5": "Monitoreo de parámetros atmosféricos con CC-06 ESS.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-5",
    "ico": "💳",
    "type": "p",
    "name": "RECAUDO PEAJE ELECTRÓNICO (EFC)",
    "para": "Sirve para automatizar el cobro, gestionar interoperabilidad TAG (IPyG), categorizar vehículos y generar reportes financieros consolidados.",
    "donde": "Plazas de peaje troncales y laterales del corredor Chía-Girardot.",
    "when": "Operación transaccional ininterrumpida (24/7/365), disponibilidad total en demanda máxima.",
    "just": "Maximizar la capacidad de paso en puntos de recaudo y asegurar operación auditable por ICCU e Interventoría.",
    "desp": "Antenas AVI/ETC de alta velocidad, cámaras OCR y sistemas de control de carril.",
    "beneficio": "Fluidez total en transporte nacional y reducción de costos logísticos por tiempos de espera.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-05",
    "area": "AS-04",
    "sub": "SUB-05",
    "se": "SE-ITS-2",
    "fn": "F-49 / F-50 / F-121",
    "cc": "CC-11 / CC-12 / CC-33",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Seguridad Transaccional Bancaria y Cifrado TAG",
    "e1": "Soberanía Financiera y Eficiencia en Recaudo Electrónico",
    "e2": "Confirmación de paso exitoso mediante CC-33 y registro en consola CCO.",
    "e3": "Ejecución de lógica F-49 para gestión de peajes e interoperabilidad.",
    "e4": "Sincronización de transacción en SUB-01 TMS con bus F-121.",
    "e5": "Captura de identificador electrónico mediante CC-11 AVI.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-6",
    "ico": "🔒",
    "type": "p",
    "name": "SOBERANÍA DEL DATO Y CIBERSEGURIDAD",
    "para": "Sirve para detectar intrusiones, mitigar ataques DDoS y garantizar autenticidad en actualizaciones de software de campo.",
    "donde": "Transversal en todos los nodos de red, armarios de campo y núcleo del CCO.",
    "cuando": "Vigilancia digital proactiva automática 24/7 con respuesta inmediata.",
    "just": "Clasificación de sistemas ITS como Infraestructura Crítica Nacional; un ciberataque tendría consecuencias fatales.",
    "desp": "Dispositivos de seguridad perimetral industrial y software SIEM en el Centro de Control.",
    "beneficio": "Protección de privacidad de usuarios y garantía de autopista resiliente e inmanipulable.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-04",
    "area": "AS-12",
    "sub": "SUB-12",
    "se": "SE-ITS-12",
    "fn": "F-120 / F-121",
    "cc": "CC-21",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Blindaje de Infraestructura Crítica (SIEM)",
    "e1": "Gobernanza Digital y Seguridad de la Información Nacional",
    "e2": "Aislamiento preventivo de segmentos de red comprometidos.",
    "e3": "Ejecución de algoritmos de encriptación en bus F-121.",
    "e4": "Análisis de tráfico de red en SUB-12 NMS para detección DDoS.",
    "e5": "Monitoreo de integridad de nodos de campo y gabinetes.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-7",
    "ico": "🔧",
    "type": "p",
    "name": "MANTENIMIENTO E INFRAESTRUCTURA (SHM)",
    "para": "Sirve para detectar fisuras, pérdida de tensión en torones e inclinación de taludes, permitiendo intervenciones preventivas.",
    "donde": "Estructuras críticas, puentes de grandes luces, túneles y zonas de inestabilidad geológica.",
    "cuando": "Vigilancia pasiva permanente con reportes diagnósticos y alertas inmediatas ante eventos sísmicos.",
    "just": "Proteger inversión multimillonaria; los datos científicos eliminan subjetividad de inspecciones visuales.",
    "desp": "Inclinómetros, sensores de deformación y acelerómetros conectados a fibra óptica.",
    "beneficio": "Seguridad total para el viajero en estructuras certificadas digitalmente.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-06",
    "area": "AS-11",
    "sub": "SUB-06",
    "se": "SE-ITS-8",
    "fn": "F-120 / F-122",
    "cc": "CC-08 / CC-09 / CC-40",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Integridad de Telemetría Geotécnica",
    "e1": "Ciclo de Vida de Activos y Salud Estructural Digital",
    "e2": "Generación de órdenes de mantenimiento preventivo desde el CCO.",
    "e3": "Ejecución de función F-122 para visualización deformadaen 3D.",
    "e4": "Integración de data en SUB-10 ESB para análisis de salud estructural.",
    "e5": "Captura de desplazamientos mediante CC-08 GMS-I.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-8",
    "ico": "📡",
    "type": "p",
    "name": "RESILIENCIA DE RED Y COMUNICACIONES",
    "para": "Sirve para asegurar que las alertas lleguen al CCO sin latencia, que el recaudo no se detenga y la supervisión sea constante.",
    "donde": "Longitud total del corredor, nodos de agregación y enlace troncal CCO.",
    "cuando": "Vigilancia de red 24/7 con protocolos de conmutación en milisegundos.",
    "just": "Resiliencia de red es el soporte de todos los servicios prioritarios PMITS.",
    "desp": "Anillo de fibra óptica redundante y estaciones de backhaul satelital.",
    "beneficio": "Confianza total en disponibilidad de servicios de auxilio sin importar incidentes externos.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-04",
    "area": "AS-12",
    "sub": "SUB-12",
    "se": "SE-ITS-12",
    "fn": "F-120 / F-121",
    "cc": "CC-23 / CC-42",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Core de Red Resiliente e Inmune a Interferencias",
    "e1": "Continuidad de Misión Crítica y Soberanía Tecnológica",
    "e2": "Alerta de degradación de red y despacho de equipo de mantenimiento.",
    "e3": "Uso de función F-121 para orquestación entre canales redundantes.",
    "e4": "Gestión de rutas en SUB-12 NMS priorizando paquetes críticos.",
    "e5": "Tráfico a través de CC-23 FOC con respaldo automático CC-42.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-9",
    "ico": "📷",
    "type": "p",
    "name": "FISCALIZACIÓN Y CONTROL (ALPR)",
    "para": "Sirve para alertar sobre vehículos hurtados, fiscalizar normas técnicas y generar estadísticas de evasión.",
    "donde": "Puntos de entrada/salida, peajes y zonas de alta afluencia vehicular.",
    "cuando": "Operación automática 24/7 con generación de alertas en tiempo real (lista negra).",
    "just": "Mejorar estándares de legalidad en vías nacionales y control equitativo.",
    "desp": "Cámaras OCR de alta definición y software de analítica de video seguros.",
    "beneficio": "Mejora de seguridad pública y fomento de legalidad en sector transporte.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-04",
    "area": "AS-05",
    "sub": "SUB-08",
    "se": "SE-ITS-5",
    "fn": "F-119 / F-118",
    "cc": "CC-12 / CC-01",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Protección de Bases de Datos de Autoridades",
    "e1": "Seguridad Ciudadana y Aplicación Directa de la Ley",
    "e2": "Notificación inmediata a patrulla de policía vía radio.",
    "e3": "Ejecución de función F-119 para detección de infracciones.",
    "e4": "Cruce de información en SUB-08 TES con autoridades externas.",
    "e5": "Captura del dominio vehicular mediante CC-12 ALPR.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-10",
    "ico": "⚡",
    "type": "c",
    "name": "GESTIÓN DE ELECTROMOVILIDAD",
    "para": "Sirve para informar sobre cargadores, gestionar cobro y monitorear carga eléctrica total para evitar picos.",
    "donde": "Áreas de Servicio y puntos de descanso estratégicos.",
    "cuando": "Disponibilidad 24/7 con monitoreo preventivo de operatividad.",
    "just": "Compromiso nacional de reducción de GEI y soporte de vehículos del futuro.",
    "desp": "Estaciones de carga rápida y micro-red energética inteligente.",
    "beneficio": "Reducción de contaminación y fomento de transporte limpio y económico.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-06",
    "area": "AS-11",
    "sub": "SUB-06",
    "se": "SE-ITS-10",
    "fn": "F-120 / F-121",
    "cc": "CC-16 / CC-39",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Protección de Redes Smart-Grid",
    "e1": "Transición Energética y Movilidad de Bajas Emisiones",
    "e2": "Publicación de disponibilidad en canales digitales y App.",
    "e3": "Uso de función F-121 para integración de pagos de servicio.",
    "e4": "Gestión de disponibilidad en SUB-12 NMS informando ocupación.",
    "e5": "Suministro de energía y monitoreo mediante CC-16 EVCS.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-11",
    "ico": "💡",
    "type": "c",
    "name": "TELEGESTIÓN Y EFICIENCIA ENERGÉTICA",
    "para": "Sirve para automatizar encendido/apagado, detectar robos de cableado y programar atenuación (dimming).",
    "donde": "Iluminación de túneles, plazas de peaje y tramos urbanos.",
    "cuando": "Gestión 24/7 con planes de ahorro en bajo flujo vehicular.",
    "just": "Gestión moderna y austera de recursos; elimina patrullajes de detección de fallas.",
    "desp": "Controladores inteligentes y medidores bidireccionales en fibra óptica.",
    "beneficio": "Reducción de impacto lumínico y mayor seguridad en túneles.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-06",
    "area": "AS-11",
    "sub": "SUB-06",
    "se": "SE-ITS-8",
    "fn": "F-120 / F-121",
    "cc": "CC-29 / CC-20",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Control Remoto de Actuadores Críticos",
    "e1": "Sostenibilidad Energética y Optimización de Activos",
    "e2": "Ajuste remoto de intensidad lumínica desde el CCO.",
    "e3": "Ejecución de función F-121 para integración de datos de potencia.",
    "e4": "Gestión de lógica de ahorro en SUB-06 AMS punto a punto.",
    "e5": "Monitoreo de consumo y estado físico mediante CC-29 SLP.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-12",
    "ico": "📶",
    "type": "f",
    "name": "CONECTIVIDAD V2X / I2V",
    "para": "Sirve para difundir alertas personalizadas y habilitar asistencia avanzada a la conducción.",
    "donde": "Puntos ciegos, zonas de alta siniestralidad y túneles.",
    "cuando": "Difusión continua con activación ante incidentes detectados.",
    "just": "Eliminar errores humanos de percepción mediante tecnología disruptiva.",
    "desp": "Unidades RSU en postes estratégicos integradas a baja latencia.",
    "beneficio": "Reducción drástica de colisiones por alcance y agilidad en emergencias.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-03",
    "area": "AS-02",
    "sub": "SUB-02",
    "se": "SE-ITS-1",
    "fn": "F-121 / F-02",
    "cc": "CC-26 / CC-25",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Autenticidad de Mensajes de Seguridad V2X",
    "e1": "Conectividad Total y Autopistas Inteligentes 5G",
    "e2": "Publicación automática de alerta en entorno de vehículo.",
    "e3": "Uso de función F-121 para orquestación segura de datos externos.",
    "e4": "Orquestación de mensajes en SUB-02 TIS priorizando alertas.",
    "e5": "Difusión de tramas inalámbricas mediante CC-26 RSU.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-13",
    "ico": "🤖",
    "type": "f",
    "name": "GESTIÓN DE VEHÍCULOS AUTÓNOMOS",
    "para": "Sirve para validar entorno operativo y coordinar maniobras colectivas (Truck Platooning).",
    "donde": "Tramos rectos de alta visibilidad y corredores exclusivos de carga.",
    "cuando": "Operación experimental asistida evolucionando a tráfico masivo.",
    "just": "Competitividad logística; requiere vía capaz de certificar digitalmente el entorno.",
    "desp": "Uso intensivo de RSU y unidades Edge-Computing CC-21.",
    "beneficio": "Reducción total de accidentes por fatiga y optimización de flujo.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-01",
    "area": "AS-08",
    "sub": "SUB-11",
    "se": "SE-ITS-6",
    "fn": "F-121 / F-122",
    "cc": "CC-26 / CC-21",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Latencia Zero y Control de Borde Seguro",
    "e1": "Logística Autónoma y Transporte del Futuro",
    "e2": "Monitoreo prioritario de convoyes con intervención remota.",
    "e3": "Uso de función F-121 para integración de telemetría de vehículo.",
    "e4": "Gestión de flujo en SUB-07 CVO supervisando trayectorias.",
    "e5": "Comunicación de baja latencia mediante CC-26 RSU.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-14",
    "ico": "📊",
    "type": "c",
    "name": "ECONOMÍA DEL DATO Y MONETIZACIÓN",
    "para": "Sirve para vender predicciones, proveer reportes a aseguradoras y alimentar Apps globales.",
    "donde": "Gestión centralizada en el Data Center del CCO.",
    "cuando": "Procesamiento de datos en tiempo real con entregas analíticas.",
    "just": "Big Data es el nuevo petróleo; el corredor es el principal generador regional.",
    "desp": "Servidores de alto rendimiento para Gemelo Digital CC-40.",
    "beneficio": "Fomento de innovación y reducción de carga fiscal sobre el peaje.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-01",
    "area": "AS-12",
    "sub": "SUB-10",
    "se": "SE-ITS-12",
    "fn": "F-121 / F-122",
    "cc": "CC-40 / CC-21",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Anonimización y Protección de Privacidad (B2B)",
    "e1": "Economía del Conocimiento y Monetización de Activos Digitales",
    "e2": "Monitoreo de salud transaccional de APIs desde el CCO.",
    "e3": "Uso de función F-121 para orquestación hacia externos.",
    "e4": "Gestión de soberanía y acceso en SUB-10 ESB.",
    "e5": "Captura integral y almacenamiento fidelidad en CC-40 D-TWN.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  },
  {
    "id": "EOV-15",
    "ico": "🌿",
    "type": "f",
    "name": "AUTOPISTA NET ZERO",
    "para": "Sirve para cuantificar ahorro de emisiones, alertar contaminación y optimizar energía renovable.",
    "donde": "Longitud de corredor con estaciones de aire y parques solares.",
    "cuando": "Vigilancia ambiental y energética continua (24/7).",
    "just": "Compromiso Acuerdo de París y Política Nacional de Cambio Climático.",
    "desp": "Sensores AQM y micro-red inteligente MSG.",
    "beneficio": "Mejora calidad del aire y reducción dependencia energética nacional.",
    "actores": "Concesión, Interventoría, Ministerio de Transporte, ICCU, DITRA.",
    "dominio": "DOM-06",
    "area": "AS-06",
    "sub": "SUB-09",
    "se": "SE-ITS-7",
    "fn": "F-120 / F-10",
    "cc": "CC-31 / CC-39",
    "std": "ISO 14813 / ARC-IT V9 / DATEX II",
    "cyber": "Gobernanza de Créditos de Carbono Digitales",
    "e1": "Carbono Neutralidad y Autopista Verde Inteligente",
    "e2": "Ajuste táctico de flujos para reducir congestión (emisiones).",
    "e3": "Uso de función F-120 para monitoreo de redes de servicio.",
    "e4": "Gestión de sostenibilidad en SUB-09 ESS-M.",
    "e5": "Monitoreo de emisiones mediante CC-31 AQM.",
    "reflejo": "Monitoreo Real-Time",
    "conciencia": "CC-40 D-TWN",
    "estadio": "Gestión Proactiva",
    "alertas": ["Alerta Nivel 1 (Meta: <30s)", "Falla de componente (Meta: <1h)", "Ciberataque (Meta: 0)", "Desviación umbral", "Error lógico"],
    "kpis": ["KPI Disponibilidad >99%", "KPI Eficiencia >15%", "KPI Calidad Dato >98%", "KPI Seguridad 0 fallas", "KPI Respuesta <1 min"]
  }
];
